-- NB: This file is shared between the MWSE and OpenMW implementations


-- The effect costs for most summons were initially calculated by mort using a formula (dependent on a creature's health and soul) that is now lost and were then adjusted as seemed reasonable.
-- Calculations have provided a new formula: Effect Cost = (.16 * Health) + (.035 * Soul); most of the old values are in close agreement with the new formula and have thus been left unchanged.
-- effect id, effect name, creature id, effect mana cost, icon, effect description
local td_summon_effects = {
	{ "T_summon_Devourer", "summonDevourer", "T_Dae_Cre_Devourer_01", 52, "td\\s\\td_s_summ_dev.dds", "summonDevourerDesc", "summonHunger" },
	{ "T_summon_DremArch", "summonDremoraArcher", "T_Dae_Cre_Drem_Arch_01", 33, "td\\s\\td_s_sum_drm_arch.dds", "summonDremoraArcherDesc", "summonHunger" },
	{ "T_summon_DremCast", "summonDremoraCaster", "T_Dae_Cre_Drem_Cast_01", 31, "td\\s\\td_s_sum_drm_mage.dds", "summonDremoraCasterDesc", "summonHunger" },
	{ "T_summon_Guardian", "summonGuardian", "T_Dae_Cre_Guardian_01", 69, "td\\s\\td_s_sum_guard.dds", "summonGuardianDesc", "summonHunger" },
	{ "T_summon_LesserClfr", "summonLesserClannfear", "T_Dae_Cre_LesserClfr_01", 19, "td\\s\\td_s_sum_lsr_clan.dds", "summonLesserClannfearDesc", "summonHunger" },
	{ "T_summon_Ogrim", "summonOgrim", "ogrim", 33, "td\\s\\td_s_summ_ogrim.dds", "summonOgrimDesc", "summonHunger" },
	{ "T_summon_Seducer", "summonSeducer", "T_Dae_Cre_Seduc_01", 52, "td\\s\\td_s_summ_sed.dds", "summonSeducerDesc", "summonHunger" },
	{ "T_summon_SeducerDark", "summonSeducerDark", "T_Dae_Cre_SeducDark_02", 75, "td\\s\\td_s_summ_d_sed.dds", "summonSeducerDarkDesc", "summonHunger" },
	{ "T_summon_Vermai", "summonVermai", "T_Dae_Cre_Verm_01", 29, "td\\s\\td_s_summ_vermai.dds", "summonVermaiDesc", "summonHunger" },
	{ "T_summon_AtroStormMon", "summonStormMonarch", "T_Dae_Cre_MonarchSt_01", 60, "td\\s\\td_s_sum_stm_monch.dds", "summonStormMonarchDesc", "summonHunger" },
	{ "T_summon_IceWraith", "summonIceWraith", "T_Sky_Cre_IceWr_01", 35, "td\\s\\td_s_sum_ice_wrth.dds", "summonIceWraithDesc", "callBear" },
	{ "T_summon_DweSpectre", "summonDweSpectre", "dwarven ghost", 17, "td\\s\\td_s_sum_dwe_spctre.dds", "summonDweSpectreDesc", "summonAncestralGhost" },
	{ "T_summon_SteamCent", "summonSteamCent", "centurion_steam", 29, "td\\s\\td_s_sum_dwe_cent.dds", "summonSteamCentDesc", "summonCenturionSphere" },
	{ "T_summon_SpiderCent", "summonSpiderCent", "centurion_spider", 15, "td\\s\\td_s_sum_dwe_spdr.dds", "summonSpiderCentDesc", "summonCenturionSphere" },
	{ "T_summon_WelkyndSpirit", "summonWelkyndSpirit", "T_Ayl_Cre_WelkSpr_01", 29, "td\\s\\td_s_sum_welk_srt.dds", "summonWelkyndSpiritDesc", "callBear" },
	{ "T_summon_Auroran", "summonAuroran", "T_Dae_Cre_Auroran_01", 46, "td\\s\\td_s_sum_auro.dds", "summonAuroranDesc", "summonHunger" },
	{ "T_summon_Herne", "summonHerne", "T_Dae_Cre_Herne_01", 18, "td\\s\\td_s_sum_herne.dds", "summonHerneDesc", "summonHunger" },
	{ "T_summon_Morphoid", "summonMorphoid", "T_Dae_Cre_Morphoid_01", 21, "td\\s\\td_s_sum_morph.dds", "summonMorphoidDesc", "summonHunger" },
	{ "T_summon_Draugr", "summonDraugr", "T_Sky_Und_Drgr_01", 29, "td\\s\\td_s_sum_draugr.dds", "summonDraugrDesc", "summonAncestralGhost" },
	{ "T_summon_Spriggan", "summonSpriggan", "T_Sky_Cre_Spriggan_01", 48, "td\\s\\td_s_sum_sprig.dds", "summonSprigganDesc", "callBear" },
	{ "T_summon_BoneldGr", "summonGreaterBonelord", "T_Mw_Und_BoneldGr_01", 71, "td\\s\\td_s_sum_gtr_bnlrd.dds", "summonGreaterBonelordDesc", "summonAncestralGhost" },
	{ "T_summon_Ghost", "summonGhost", "T_Cyr_Und_Ghst_01", 7, "td\\s\\td_s_summ_ghost.dds", "summonGhostDesc", "summonAncestralGhost" },
	{ "T_summon_Wraith", "summonWraith", "T_Cyr_Und_Wrth_01", 49, "td\\s\\td_s_summ_wraith.dds", "summonWraithDesc", "summonAncestralGhost" },
	{ "T_summon_Barrowguard", "summonBarrowguard", "T_Cyr_Und_Mum_01", 11, "td\\s\\td_s_summ_brwgurd.dds", "summonBarrowguardDesc", "summonAncestralGhost" },
	{ "T_summon_MinoBarrowguard", "summonMinoBarrowguard", "T_Cyr_Und_MinoBarrow_01", 57, "td\\s\\td_s_summ_mintur.dds", "summonMinoBarrowguardDesc", "summonAncestralGhost" },
	{ "T_summon_SkeletonChampion", "summonSkeletonChampion", "T_Glb_Und_SkelCmpGls_01", 32, "td\\s\\td_s_sum_skele_c.dds", "summonSkeletonChampionDesc", "summonAncestralGhost" },
	{ "T_summon_AtroFrostMon", "summonFrostMonarch", "T_Dae_Cre_MonarchFr_01", 47, "td\\s\\td_s_sum_fst_monch.dds", "summonFrostMonarchDesc", "summonHunger" },
	{ "T_summon_SpiderDaedra", "summonSpiderDaedra", "T_Dae_Cre_SpiderDae_01", 42, "td\\s\\td_s_sum_spidr_dae.dds", "summonSpiderDaedraDesc", "summonHunger" },
}

-- effect id, effect name, item id, 2nd item ID, effect mana cost, icon, effect description
local td_bound_effects = {
	{ "T_bound_Greaves", "boundGreaves", "T_Com_Bound_Greaves_01", "", 2, "td\\s\\td_s_bnd_grves.dds", "boundGreavesDesc"},
	{ "T_bound_Waraxe", "boundWarAxe", "T_Com_Bound_WarAxe_01", "", 2, "td\\s\\td_s_bnd_waxe.dds", "boundWarAxeDesc"},
	{ "T_bound_Warhammer", "boundWarhammer", "T_Com_Bound_Warhammer_01", "", 2, "td\\s\\td_s_bnd_wham.dds", "boundWarhammerDesc"},
	{ "T_bound_HammerResdayn", "", "T_Com_Bound_Warhammer_01", "", 2, "td\\s\\td_s_bnd_res_ham.dds", ""},
	{ "T_bound_RazorResdayn", "", "bound_dagger", "", 2, "td\\s\\td_s_bnd_red_razor.dds", ""},
	{ "T_bound_Pauldrons", "boundPauldrons", "T_Com_Bound_PauldronL_01", "T_Com_Bound_PauldronR_01", 2, "td\\s\\td_s_bnd_pldrn.dds", "boundPauldronsDesc"},
	{ "T_bound_Greatsword", "boundClaymore", "T_Com_Bound_Claymore_01", "", 2, "td\\s\\td_s_bnd_clymr.dds", "boundClaymoreDesc"},
	{ "T_bound_ThrowingKnives", "boundThrowingKnives", "T_Com_Bound_ThrowingKnife_01", "", 2, "td\\s\\td_s_bnd_knives.dds", "boundThrowingKnivesDesc"},
}

-- effect id, effect name, effect mana cost, icon, effect description
local td_intervention_effects = {
	{ "T_intervention_Kyne", "interventionKyne", 150, "td\\s\\td_s_int_kyne.tga", "interventionKyneDesc"},
}

-- effect id, effect name, effect mana cost, icon, effect description
local td_misc_effects = {
	{ "T_mysticism_Passwall", "miscPasswall", 750, "td\\s\\td_s_passwall.tga", "miscPasswallDesc"},
	{ "T_mysticism_BanishDae", "miscBanish", 128, "td\\s\\td_s_ban_daedra.tga", "miscBanishDesc"},
	{ "T_mysticism_ReflectDmg", "miscReflectDamage", 20, "td\\s\\td_s_ref_dam.tga", "miscReflectDamageDesc"},
	{ "T_mysticism_DetHuman", "miscDetectHumanoid", .75, "td\\s\\td_s_det_hum.tga", "miscDetectHumanoidDesc"},
	{ "T_alteration_RadShield", "miscRadiantShield", 5, "td\\s\\td_s_radiant_shield.tga", "miscRadiantShieldDesc"},
	{ "T_alteration_Wabbajack", "miscWabbajack", 22, "td\\s\\td_s_wabbajack.tga", "miscWabbajackDesc"},
	{ "T_alteration_WabbajackHelper", "miscWabbajack", 0, "td\\s\\td_s_wabbajack.tga", "miscWabbajackDesc"},
	{ "T_mysticism_Insight", "miscInsight", 10, "td\\s\\td_s_insight.tga", "miscInsightDesc"},
	{ "T_restoration_ArmorResartus", "miscArmorResartus", 60, "td\\s\\td_s_restore_ar.tga", "miscArmorResartusDesc"},
	{ "T_restoration_WeaponResartus", "miscWeaponResartus", 120, "td\\s\\td_s_restore_wpn.tga", "miscWeaponResartusDesc"},
	{ "T_conjuration_Corruption", "miscCorruption", 40, "td\\s\\td_s_skull_corr.tga", "miscCorruptionDesc"},
	{ "T_conjuration_CorruptionSummon", "miscCorruption", 0, "td\\s\\td_s_skull_corr.tga", "miscCorruptionDesc"},
	{ "T_illusion_DistractCreature", "miscDistractCreature", 0.5, "td\\s\\td_s_dist_cre.tga", "miscDistractCreatureDesc"},
	{ "T_illusion_DistractHumanoid", "miscDistractHumanoid", 1, "td\\s\\td_s_dist_hum.tga", "miscDistractHumanoidDesc"},
	{ "T_destruction_GazeOfVeloth", "miscGazeOfVeloth", 80, "td\\s\\td_s_gaze_veloth.tga", "miscGazeOfVelothDesc"},
	{ "T_mysticism_DetEnemy", "miscDetectEnemy", 1, "td\\s\\td_s_det_enemy.tga", "miscDetectEnemyDesc"},
	{ "T_mysticism_DetInvisibility", "miscDetectInvisibility", 1.5, "td\\s\\td_s_det_invisibility.tga", "miscDetectInvisibilityDesc"},
	{ "T_mysticism_Blink", "miscBlink", 10, "td\\s\\td_s_blink.tga", "miscBlinkDesc"},
	{ "T_restoration_FortifyCasting", "miscFortifyCasting", 1, "td\\s\\td_s_ftfy_cast.tga", "miscFortifyCastingDesc"},
	{ "T_illusion_PrismaticLight", "miscPrismaticLight", 0.4, "td\\s\\td_s_p_light.tga", "miscPrismaticLightDesc"},
	{ "T_mysticism_BloodMagic", "miscBloodMagic", 2, "td\\s\\td_s_blood_magic.tga", "miscBloodMagicDesc"},
	{ "T_conjuration_SanguineRose", "miscSanguineRose", 40, "td\\s\\td_s_sanguine.dds.tga", "miscSanguineRoseDesc"},
	{ "T_mysticism_DetValuables", "miscDetectValuables", 1.5, "td\\s\\td_s_det_value.tga", "miscDetectValuablesDesc"},
	{ "T_mysticism_MagickaWard", "miscMagickaWard", 20, "td\\s\\td_s_magickaward.tga", "miscMagickaWardDesc"},
	{ "T_illusion_Ethereal", "miscEthereal", 40, "td\\s\\td_s_ethereal.tga", "miscEtherealtDesc"},
}

-- spell id, cast type, spell name, spell mana cost, effect1, ...
local td_summon_spells = {
	{ "T_Com_Cnj_SummonDevourer", "spell", "summonDevourer", 156, { id = "T_summon_Devourer", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonDremoraArcher", "spell", "summonDremoraArcher", 98, { id = "T_summon_DremArch", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonDremoraCaster", "spell", "summonDremoraCaster", 93, { id = "T_summon_DremCast", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonGuardian", "spell", "summonGuardian", 155, { id = "T_summon_Guardian", range = "self", duration = 45, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonLesserClannfear", "spell", "summonLesserClannfear", 57, { id = "T_summon_LesserClfr", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonOgrim", "spell", "summonOgrim", 99, { id = "T_summon_Ogrim", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonSeducer", "spell", "summonSeducer", 156, { id = "T_summon_Seducer", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonSeducerDark", "spell", "summonSeducerDark", 169, { id = "T_summon_SeducerDark", range = "self", duration = 45, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonVermai", "spell", "summonVermai", 88, { id = "T_summon_Vermai", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonStormMonarch", "spell", "summonStormMonarch", 180, { id = "T_summon_AtroStormMon", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Nor_Cnj_SummonIceWraith", "spell", "summonIceWraith", 105, { id = "T_summon_IceWraith", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Dwe_Cnj_Uni_SummonDweSpectre", "spell", "summonDweSpectre", 52, { id = "T_summon_DweSpectre", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Dwe_Cnj_Uni_SummonSteamCent", "spell", "summonSteamCent", 88, { id = "T_summon_SteamCent", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Dwe_Cnj_Uni_SummonSpiderCent", "spell", "summonSpiderCent", 45, { id = "T_summon_SpiderCent", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Ayl_Cnj_SummonWelkyndSpirit", "spell", "summonWelkyndSpirit", 78, { id = "T_summon_WelkyndSpirit", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonAuroran", "spell", "summonAuroran", 138, { id = "T_summon_Auroran", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonHerne", "spell", "summonHerne", 54, { id = "T_summon_Herne", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonMorphoid", "spell", "summonMorphoid", 63, { id = "T_summon_Morphoid", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Nor_Cnj_SummonDraugr", "spell", "summonDraugr", 78, { id = "T_summon_Draugr", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Nor_Cnj_SummonSpriggan", "spell", "summonSpriggan", 144, { id = "T_summon_Spriggan", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_De_Cnj_SummonGreaterBonelord", "spell", "summonGreaterBonelord", 160, { id = "T_summon_BoneldGr", range = "self", duration = 45, min = 1, max = 1 } },
	{ "T_Cr_Cnj_AylSorcKSummon1", "spell", nil, 40, { id = "T_summon_Auroran", range = "self", duration = 40, min = 1, max = 1 } },
	{ "T_Cr_Cnj_AylSorcKSummon3", "spell", nil, 25, { id = "T_summon_WelkyndSpirit", range = "self", duration = 40, min = 1, max = 1 } },
	{ "T_Cyr_Cnj_SummonGhost", "spell", "summonGhost", 21, { id = "T_summon_Ghost", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Cyr_Cnj_SummonWraith", "spell", "summonWraith", 147, { id = "T_summon_Wraith", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Cyr_Cnj_SummonBarrowguard", "spell", "summonBarrowguard", 33, { id = "T_summon_Barrowguard", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Cyr_Cnj_SummonMinoBarrowguard", "spell", "summonMinoBarrowguard", 171, { id = "T_summon_MinoBarrowguard", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonSkeletonChamp", "spell", "summonSkeletonChampion", 96, { id = "T_summon_SkeletonChampion", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonFrostMonarch", "spell", "summonFrostMonarch", 141, { id = "T_summon_AtroFrostMon", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_SummonSpiderDaedra", "spell", "summonSpiderDaedra", 126, { id = "T_summon_SpiderDaedra", range = "self", duration = 60, min = 1, max = 1 } },
}

-- spell id, cast type, spell name, spell mana cost, effect1, ...
local td_bound_spells = {
	{ "T_Com_Cnj_BoundGreaves", "spell", "boundGreaves", 6, { id = "T_bound_Greaves", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_BoundWarAxe", "spell", "boundWarAxe", 6, { id = "T_bound_Waraxe", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_BoundWarhammer", "spell", "boundWarhammer", 6, { id = "T_bound_Warhammer", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_De_Cnj_Uni_BoundHammerResdayn", "spell", nil, 6, { id = "T_bound_HammerResdayn", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_De_Cnj_Uni_BoundRazorOResdayn", "spell", nil, 6, { id = "T_bound_RazorResdayn", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_BoundPauldron", "spell", "boundPauldrons", 6, { id = "T_bound_Pauldrons", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Com_Cnj_BoundGreatsword", "spell", "boundClaymore", 6, { id = "T_bound_Greatsword", range = "self", duration = 60, min = 1, max = 1 } },
	--{ "T_Com_Cnj_BoundThrowingKnives", "spell", "boundThrowingKnives", 6, { id = "T_bound_ThrowingKnives", range = "self", duration = 10, min = 1, max = 1 } },
}

-- spell id, cast type, spell name, spell mana cost, effect1, ...
local td_intervention_spells = {
	{ "T_Nor_Mys_KynesIntervention", "spell", "interventionKyne", 8, { id = "T_intervention_Kyne", range = "self", min = 1, max = 1 } },
}

-- spell id, cast type, spell name, spell mana cost, effect1, ...
local td_misc_spells = {
	{ "T_Com_Mys_UNI_Passwall", "spell", "miscPasswall", 96, { id = "T_mysticism_Passwall", range = "touch", area = 25 } },
	{ "T_Com_Mys_BanishDaedra", "spell", "miscBanish", 64, { id = "T_mysticism_BanishDae", range = "touch", min = 10, max = 10 } },
	{ "T_Com_Mys_ReflectDamage", "spell", "miscReflectDamage", 76, { id = "T_mysticism_ReflectDmg", range = "self", duration = 5, min = 10, max = 20 } },
	{ "T_Com_Mys_DetectHumanoid", "spell", "miscDetectHumanoid", 19, { id = "T_mysticism_DetHuman", range = "self", duration = 5, min = 50, max = 150 } },
	--{ "T_Ayl_Alt_RadiantShield", "spell", "miscRadiantShield", 75, { id = "T_alteration_RadShield", range = "self", duration = 30, min = 10, max = 10 } },	-- Not currently in TD
	{ "T_Cr_Alt_AuroranShield", "ability", nil, nil, { id = "T_alteration_RadShield", range = "self", min = 20, max = 20 } },
	{ "T_Cr_Alt_AylSorcKLightShield", "spell", "miscRadiantShield", 10, { id = "T_alteration_RadShield", range = "self", duration = 12, min = 10, max = 10 },
																		{ id = "light", range = "self", duration = 12, min = 20, max = 20 } },
	{ "T_Com_Mys_Insight", "spell", "miscInsight", 76, { id = "T_mysticism_Insight", range = "self", duration = 10, min = 15, max = 15 } },
	{ "T_Com_Res_ArmorResartus", "spell", "miscArmorResartus", 90, { id = "T_restoration_ArmorResartus", range = "self", min = 20, max = 40 } },
	{ "T_Com_Res_WeaponResartus", "spell", "miscWeaponResartus", 90, { id = "T_restoration_WeaponResartus", range = "self", min = 10, max = 20 } },
	{ "T_Dae_Cnj_UNI_CorruptionSummon", "spell", "miscCorruption", 0, { id = "T_conjuration_CorruptionSummon", range = "self", duration = 30, min = 1, max = 1 } },
	{ "T_Com_Ilu_DistractCreature", "spell", "miscDistractCreature", 11, { id = "T_illusion_DistractCreature", range = "target", duration = 15, min = 20, max = 20 } },
	{ "T_Com_Ilu_DistractHumanoid", "spell", "miscDistractHumanoid", 22, { id = "T_illusion_DistractHumanoid", range = "target", duration = 15, min = 20, max = 20 } },
	{ "T_Com_Mys_DetectEnemy", "spell", "miscDetectEnemy", 25, { id = "T_mysticism_DetEnemy", range = "self", duration = 5, min = 50, max = 150 } },
	{ "T_Dae_Alt_UNI_WabbajackTrans", "spell", "miscWabbajack", 0, { id = "T_alteration_WabbajackHelper", range = "touch", duration = 16, min = 1, max = 1 } },
	{ "T_Com_Mys_DetectInvisibility", "spell", "miscDetectInvisibility", 38, { id = "T_mysticism_DetInvisibility", range = "self", duration = 5, min = 50, max = 150 } },
	{ "T_Com_Mys_Blink", "spell", "miscBlink", 25, { id = "T_mysticism_Blink", range = "self", min = 50, max = 50 } },
	--{ "T_Cr_Ab_AuroranLight", "ability", nil, nil, { id = "T_illusion_PrismaticLight", range = "self", min = 20, max = 20 } },	-- There should be a separate, higher magnitude ability for the radiant Aurorans that will be affected instead
	{ "T_UNI_SaintTelynBlessing", "ability", nil, nil, { id = "T_mysticism_Insight", range = "self", min = 10, max = 10 } },
	{ "T_Arg_Mys_BloodMagic", "power", nil, nil, { id = "T_mysticism_BloodMagic", range = "self", duration = 90 } },
	{ "T_Com_Mys_BloodMagic", "spell", "miscBloodMagic", 3, { id = "T_mysticism_BloodMagic", range = "self", duration = 30 } },
	{ "T_Com_Mys_DetectValuables", "spell", "miscDetectValuables", 38, { id = "T_mysticism_DetValuables", range = "self", duration = 5, min = 50, max = 150 } },
	{ "T_Com_Mys_MagickaWard", "spell", "miscMagickaWard", 20, { id = "T_mysticism_MagickaWard", range = "self", duration = 20, min = 1, max = 1 } },
	{ "T_Com_Ilu_Ethereal", "spell", "miscEthereal", 30, { id = "T_illusion_Ethereal", range = "self", duration = 15, min = 1, max = 1 } },
	{ "T_Nag_Pow_StalkersShroud", "power", nil, nil, { id = "chameleon", range = "self", duration = 60, min = 50, max = 50 },
													{ id = "T_mysticism_DetHuman", range = "self", duration = 60, min = 100, max = 100 } },
}

-- enchantment id, type, effect1, ...
local td_enchantments = {
	{ "T_Once_SummonDremoraArcher60", "castOnce", { id = "T_summon_DremArch", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonDremoraCaster60", "castOnce", { id = "T_summon_DremCast", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonGuardian60", "castOnce", { id = "T_summon_Guardian", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonLesserClannfear60", "castOnce", { id = "T_summon_LesserClfr", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonOgrim60", "castOnce", { id = "T_summon_Ogrim", range = "self", duration = 60, min = 1, max = 1 }, nil },
	{ "T_Once_SummonOgrim120", "castOnce", { id = "T_summon_Ogrim", range = "self", duration = 120, min = 1, max = 1 }, nil },
	{ "T_Once_SummonSeducer60", "castOnce", { id = "T_summon_Seducer", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonSeducerDark60", "castOnce", { id = "T_summon_SeducerDark", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonVermai60", "castOnce", { id = "T_summon_Vermai", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonVermai120", "castOnce", { id = "T_summon_Vermai", range = "self", duration = 120, min = 1, max = 1 } },
	{ "T_Once_SummonSkeletonChamp120", "castOnce", { id = "T_summon_SkeletonChampion", range = "self", duration = 120, min = 1, max = 1 } },
	{ "T_Once_SummonFrostMonarch120", "castOnce", { id = "T_summon_AtroFrostMon", range = "self", duration = 120, min = 1, max = 1 } },
	{ "T_Once_SummonStormMonarch60", "castOnce", { id = "T_summon_AtroStormMon", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonWelkyndSpirit60", "castOnce", { id = "T_summon_WelkyndSpirit", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonAuroran60", "castOnce", { id = "T_summon_Auroran", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonHerne60", "castOnce", { id = "T_summon_Herne", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonMorphoid60", "castOnce", { id = "T_summon_Morphoid", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_SummonBonelordGr60", "castOnce", { id = "T_summon_BoneldGr", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_AylDaedricHerald1", "castOnce", { id = "T_summon_WelkyndSpirit", range = "self", duration = 30, min = 1, max = 1 } },
	{ "T_Once_AylDaedricHerald2", "castOnce", { id = "T_summon_Auroran", range = "self", duration = 30, min = 1, max = 1 } },
	{ "T_Once_AylLoreArmor1", "castOnce", { id = "T_alteration_RadShield", range = "self", duration = 30, min = 20, max = 20 } },
	--{ "T_Once_AylCavernsTruth", "castOnce", { id = "T_illusion_PrismaticLight", range = "self", duration = 90, min = 15, max = 15 } },
	{ "T_Once_KynesIntervention", "castOnce", { id = "T_intervention_Kyne", range = "self", duration = 1, min = 1, max = 1 } },
	{ "T_Once_QuelledGeas", "castOnce", { id = "T_mysticism_BanishDae", range = "touch", duration = 1, min = 10, max = 15 } },
	{ "T_Once_LordMhasFortress", "castOnce", { id = "boundBoots", range = "self", duration = 90, min = 1, max = 1 },
																{ id = "T_bound_Greaves", range = "self", duration = 90, min = 1, max = 1 },
																{ id = "boundCuirass", range = "self", duration = 90, min = 1, max = 1 },
																{ id = "T_bound_Pauldrons", range = "self", duration = 90, min = 1, max = 1 },
																{ id = "boundGloves", range = "self", duration = 90, min = 1, max = 1 },
																{ id = "boundHelm", range = "self", duration = 90, min = 1, max = 1 },
																{ id = "boundShield", range = "self", duration = 90, min = 1, max = 1 },
																{ id = "T_bound_Warhammer", range = "self", duration = 90, min = 1, max = 1 } },
	{ "T_Once_SummonDremoraAll60", "castOnce", { id = "summonDremora", range = "self", duration = 60, min = 1, max = 1 },
																{ id = "T_summon_DremArch", range = "self", duration = 60, min = 1, max = 1 },
																{ id = "T_summon_DremCast", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_DaedraBane", "castOnce", { id = "T_mysticism_BanishDae", range = "touch", duration = 1, min = 10, max = 15 } },
	{ "T_Once_BlackSpirits", "castOnce", { id = "T_mysticism_BanishDae", range = "target", area = 25, duration = 1, min = 10, max = 40 } },
	{ "T_Once_Diversion", "castOnce", { id = "T_illusion_DistractHumanoid", range = "target", duration = 30, min = 10, max = 30 } },
	{ "T_Once_Scent", "castOnce", { id = "T_illusion_DistractCreature", range = "target", duration = 30, min = 10, max = 30 } },
	{ "T_Once_DarothrilDisorder", "castOnce", { id = "T_illusion_DistractCreature", range = "target", area = 20, duration = 20, min = 50, max = 50 },
																 { id = "T_illusion_DistractHumanoid", range = "target", area = 20, duration = 20, min = 50, max = 50 } },
	{ "T_Once_Revealing", "castOnce", { id = "T_mysticism_DetInvisibility", range = "self", duration = 10, min = 40, max = 80 }, nil },
	{ "T_Once_GramaryeMirror", "castOnce", { id = "T_mysticism_ReflectDmg", range = "self", duration = 30, min = 20, max = 20 },
															{ id = "reflect", range = "self", duration = 30, min = 20, max = 20 } },
	{ "T_Once_DeificChrisom", "castOnce", { id = "T_mysticism_ReflectDmg", range = "self", duration = 60, min = 10, max = 30 },
															 { id = "spellAbsorption", range = "self", duration = 60, min = 10, max = 30 },
															 { id = "sanctuary", range = "self", duration = 60, min = 10, max = 30 } },
	{ "T_Once_Dashing", "castOnce", { id = "T_mysticism_Blink", range = "self", min = 40, max = 40 } },
	{ "T_Once_AssassinRush", "castOnce", { id = "T_mysticism_Blink", range = "self", min = 30, max = 30 },
															{ id = "fortifyAttack", range = "self", duration = 60, min = 10, max = 20 },
															{ id = "fortifySkill, nil, tes3.skill.shortBlade", range = "self", duration = 60, min = 10, max = 20 } },
	{ "T_Once_QorwynnMending", "castOnce", { id = "T_restoration_ArmorResartus", range = "self", min = 30, max = 30 },
															{ id = "T_restoration_WeaponResartus", range = "self", min = 30, max = 30 } },
	{ "T_Once_MoathAuthority", "castOnce", { id = "boundBoots", range = "self", duration = 90, min = 1, max = 1 },
															{ id = "T_bound_Greaves", range = "self", duration = 90, min = 1, max = 1 },
															{ id = "boundGloves", range = "self", duration = 90, min = 1, max = 1 },
															{ id = "T_bound_Greatsword", range = "self", duration = 90, min = 1, max = 1 } },
	{ "T_Once_AllSeeing", "castOnce", { id = "detectAnimal", range = "self", duration = 300, min = 200, max = 200 },
														 { id = "T_mysticism_DetHuman", range = "self", duration = 300, min = 200, max = 200 },
														 { id = "T_mysticism_DetEnemy", range = "self", duration = 300, min = 200, max = 200 },
														 { id = "T_mysticism_DetInvisibility", range = "self", duration = 300, min = 200, max = 200 },
														 { id = "detectEnchantment", range = "self", duration = 300, min = 200, max = 200 },
														 { id = "detectKey", range = "self", duration = 300, min = 200, max = 200 } },
	{ "T_Once_Firmament", "castOnce", { id = "fortifyAttack", range = "self", duration = 120, min = 40, max = 40 },
														 { id = "T_restoration_FortifyCasting", range = "self", duration = 120, min = 40, max = 40 },
														 { id = "fortifySkill, nil, tes3.skill.sneak", range = "self", duration = 120, min = 40, max = 40 } },
	{ "T_Once_BoethiahService", "castOnce", { id = "summonHunger", range = "self", duration = 120, min = 1, max = 1 },
															 { id = "T_summon_Devourer", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_FourArmsGoingUp", "castOnce", { id = "summonScamp", range = "self", duration = 120, min = 1, max = 1 },
															 { id = "summonDremora", range = "self", duration = 120, min = 1, max = 1 },
															 { id = "T_summon_Morphoid", range = "self", duration = 120, min = 1, max = 1 },
															 { id = "T_summon_Herne", range = "self", duration = 120, min = 1, max = 1 } },
	{ "T_Once_Anticipations", "castOnce", { id = "summonWingedTwilight", range = "self", duration = 60, min = 1, max = 1 },
															 { id = "T_summon_SpiderDaedra", range = "self", duration = 60, min = 1, max = 1 },
															 { id = "summonHunger", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Once_FourCorners", "castOnce", { id = "summonGoldenSaint", range = "self", duration = 60, min = 1, max = 1 },
														 { id = "summonDremora", range = "self", duration = 60, min = 1, max = 1 },
														 { id = "T_summon_Ogrim", range = "self", duration = 60, min = 1, max = 1 },
														 { id = "summonDaedroth", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Const_Ring_Namira", "constant", { id = "T_mysticism_ReflectDmg", range = "self", duration = 1, min = 30, max = 30 },
															{ id = "reflect", range = "self", duration = 1, min = 30, max = 30 } },
	{ "T_Const_FindersCharm", "constant", { id = "T_mysticism_Insight", range = "self", duration = 1, min = 10, max = 10 },
															 { id = "detectEnchantment", range = "self", duration = 1, min = 120, max = 120 },
															 { id = "detectKey", range = "self", duration = 1, min = 120, max = 120 } },
	{ "T_Const_Robe_Reprisal", "constant", { id = "frostShield", range = "self", duration = 1, min = 50, max = 50 },
															{ id = "T_mysticism_ReflectDmg", range = "self", duration = 1, min = 10, max = 10 } },
	{ "T_Const_Onimaru_en", "constant", { id = "fortifyAttack", range = "self", duration = 1, min = 10, max = 10 },
														 { id = "resistMagicka", range = "self", duration = 1, min = 20, max = 20 },
														 { id = "resistNormalWeapons", range = "self", duration = 1, min = 20, max = 20 },
														 { id = "T_mysticism_ReflectDmg", range = "self", duration = 1, min = 20, max = 20 },
														 { id = "summonDremora", range = "self", duration = 1, min = 1, max = 1 } },
	{ "T_Const_NadiaInsight", "constant", { id = "T_mysticism_Insight", range = "self", duration = 1, min = 30, max = 30 } },
	{ "T_Use_GuardianRIng", "onUse", { id = "boundBoots", range = "self", duration = 60, min = 1, max = 1 },						-- The ID's capitalization does match that of the enchantment in the ESM
														{ id = "T_bound_Greaves", range = "self", duration = 60, min = 1, max = 1 },
														{ id = "boundCuirass", range = "self", duration = 60, min = 1, max = 1 },
														{ id = "T_bound_Pauldrons", range = "self", duration = 60, min = 1, max = 1 },
														{ id = "boundGloves", range = "self", duration = 60, min = 1, max = 1 },
														{ id = "boundHelm", range = "self", duration = 60, min = 1, max = 1 }, },
	{ "T_Use_WabbajackUni", "onUse", { id = "T_alteration_Wabbajack", range = "target", duration = 1, min = 1, max = 1 } },
	{ "T_Use_SkullOfCorruption", "onUse", { id = "T_conjuration_Corruption", range = "target", min = 1, max = 1 } },
	{ "T_Use_SummonGuardian60", "castOnce", { id = "T_summon_Guardian", range = "self", duration = 60, min = 1, max = 1 } },			-- Not on any items?
	{ "T_Const_VelothsPauld_R", "constant", { id = "T_mysticism_ReflectDmg", range = "self", duration = 1, min = 30, max = 30 } },
	{ "T_Strike_StaffVeloth", "onUse", { id = "T_destruction_GazeOfVeloth", range = "target", duration = 1, min = 1, max = 1 } },
	{ "T_Const_Spell_Bifurcation", "constant", { id = "T_restoration_FortifyCasting", range = "self", duration = 1, min = 20, max = 20 } },
	{ "TR_m1_SanguinesRose_en", "onUse", { id = "T_conjuration_SanguineRose", range = "self", duration = 60, min = 1, max = 1 } },
	{ "T_Use_SanguineRose", "onUse", { id = "T_conjuration_SanguineRose", range = "self", duration = 60, min = 1, max = 1 } },	-- This is for a deprecated weapon rather than the amulet (that is in TR rather and not TD for some absurd reason), but it might as well get the effect too
	{ "T_Use_Dae_Amulet_Entry", "onUse", { id = "T_illusion_Ethereal", range = "self", duration = 20, min = 1, max = 1 } },
}

-- item id, item name, 1st effect, ...
local td_potions = {
	{ "T_Com_Potion_ReflectDamage_B", "itemPotionReflectDamageB", { id = "T_mysticism_ReflectDmg", duration = 8, magnitude = 5 } },
	{ "T_Com_Potion_ReflectDamage_C", "itemPotionReflectDamageC", { id = "T_mysticism_ReflectDmg", duration = 15, magnitude = 8 } },
	{ "T_Com_Potion_ReflectDamage_S", "itemPotionReflectDamageS", { id = "T_mysticism_ReflectDmg", duration = 30, magnitude = 10 } },
	{ "T_Com_Potion_ReflectDamage_Q", "itemPotionReflectDamageQ", { id = "T_mysticism_ReflectDmg", duration = 45, magnitude = 15 } },
	{ "T_Com_Potion_ReflectDamage_E", "itemPotionReflectDamageE", { id = "T_mysticism_ReflectDmg", duration = 60, magnitude = 20 } },
	{ "T_Com_Potion_Insight_B", "itemPotionInsightB", { id = "T_mysticism_Insight", duration = 8, magnitude = 5 } },
	{ "T_Com_Potion_Insight_C", "itemPotionInsightC", { id = "T_mysticism_Insight", duration = 15, magnitude = 8 } },
	{ "T_Com_Potion_Insight_S", "itemPotionInsightS", { id = "T_mysticism_Insight", duration = 30, magnitude = 10 } },
	{ "T_Com_Potion_Insight_Q", "itemPotionInsightQ", { id = "T_mysticism_Insight", duration = 45, magnitude = 15 } },
	{ "T_Com_Potion_Insight_E", "itemPotionInsightE", { id = "T_mysticism_Insight", duration = 60, magnitude = 20 } },
	{ "T_Com_Potion_Detect_Humanoid_S", "itemPotionDetectHumanoid", { id = "T_mysticism_DetHuman", duration = 15, magnitude = 10 } },
	{ "T_Com_Potion_Detect_Enemy_S", "itemPotionDetectEnemy", { id = "T_mysticism_DetEnemy", duration = 15, magnitude = 10 } },
	{ "T_Com_Potion_Detect_Invisib_S", "itemPotionDetectInvisibility", { id = "T_mysticism_DetInvisibility", duration = 15, magnitude = 10 } },
	{ "T_Com_Potion_Eyes", nil, { id = "detectAnimal", duration = 60, magnitude = 50 },
								{ id = "T_mysticism_DetHuman", duration = 60, magnitude = 50 },
								{ id = "detectEnchantment", duration = 60, magnitude = 50 },
								{ id = "detectKey", duration = 60, magnitude = 50 },
								{ id = "nightEye", duration = 60, magnitude = 50 } },
	{ "T_Com_Potion_FortifyCasting_B", nil, { id = "T_restoration_FortifyCasting", duration = 8, magnitude = 5 } },
	{ "T_Com_Potion_FortifyCasting_C", nil, { id = "T_restoration_FortifyCasting", duration = 15, magnitude = 8 } },
	{ "T_Com_Potion_FortifyCasting_S", nil, { id = "T_restoration_FortifyCasting", duration = 30, magnitude = 10 } },
	{ "T_Com_Potion_FortifyCasting_Q", nil, { id = "T_restoration_FortifyCasting", duration = 45, magnitude = 15 } },
	{ "T_Com_Potion_FortifyCasting_E", nil, { id = "T_restoration_FortifyCasting", duration = 60, magnitude = 20 } },
}

-- item id, item name, value
local td_enchanted_items = {
	{ "T_EnSc_Com_SummonDremoraArcher", "itemScSummonDremoraArcher", 295 },
	{ "T_EnSc_Com_SummonDremoraCaster", "itemScSummonDremoraCaster", 314 },
	{ "T_EnSc_Nor_KynesIntervention", "itemScKynesIntervention", nil }
}

-- ingredient id, 1st effect, ...
local td_ingredients = {
	{ "T_IngFlor_PBloomBulb_01", nil,
								 { id = "T_mysticism_ReflectDmg" },
								 nil,
								 nil },
	{ "T_IngCrea_Eyestar_01", nil,
							{ id = "T_mysticism_Insight" },
							nil,
							nil },
	{ "T_IngCrea_EyestarDae_01", nil,
								 { id = "T_mysticism_Insight" },
								 nil,
								 nil },
	{ "TR_m2_q_9_Eyestar_uni", nil,
							 { id = "T_mysticism_Insight" },
							 nil,
							 nil },
	{ "T_IngCrea_BeetleShell_01", nil,
								{ id = "T_mysticism_Insight" } },
	{ "T_IngCrea_BeetleShell_04", nil,
								{ id = "T_mysticism_ReflectDmg" } },
	{ "T_IngMine_PearlBlue_01", nil,
								nil,
								nil,
								{ id = "T_mysticism_Blink" } },
	{ "T_IngMine_PearlBlueDae_01", nil,
								 nil,
								 nil,
								 { id = "T_mysticism_Blink" } },
	{ "T_IngMine_PearlPink_01", nil,
								nil,
								{ id = "T_restoration_FortifyCasting" },
								nil },
	{ "T_IngMine_PearlPinkDae_01", nil,
								 nil,
								 { id = "T_restoration_FortifyCasting" },
								 nil },
	{ "T_IngMine_PearlKardesh_01", nil,
								 nil,
								 nil,
								 { id = "T_restoration_FortifyCasting" } },
	{ "T_IngMine_DiamondRed_01", nil,
								 nil,
								 { id = "T_mysticism_ReflectDmg" },
								 nil },
	{ "T_IngCrea_PrismaticDust_01", { id = "T_mysticism_Blink" },
									{ id = "T_mysticism_ReflectDmg" },
									nil,
									nil },
	{ "T_IngCrea_MothWingMw_02", nil,
								 nil,
								 nil,
								 { id = "T_mysticism_Insight" } },
	{ "T_IngMine_Amethyst_01", { id = "T_mysticism_DetInvisibility" },
							 nil,
							 nil,
							 nil },
	{ "T_IngMine_AmethystDae_01", { id = "T_mysticism_DetInvisibility" },
								nil,
								nil,
								nil },
	{ "T_IngFood_TGuarHide", nil,
							 nil,
							 nil,
							 { id = "T_mysticism_DetInvisibility" } },
	{ "T_IngCrea_ThresherClaw_01", nil,
								 nil,
								 nil,
								 { id = "T_mysticism_DetEnemy" } },
	{ "T_IngFlor_TempleDome_01", nil,
								 nil,
								 { id = "T_mysticism_DetInvisibility" },
								 nil },
	{ "T_IngCrea_ArmunHide_01", nil,
								{ id = "T_mysticism_DetHuman" },
								nil,
								nil, },
	{ "T_IngCrea_RakiTeeth_01", nil,
								nil,
								{ id = "T_mysticism_DetHuman" },
								nil, },
	{ "T_IngCrea_Dragonscales_01", nil,
								 { id = "T_mysticism_DetEnemy" },
								 nil,
								 nil },
	{ "T_IngCrea_DridreaSilk_01", nil,
								nil,
								{ id = "T_mysticism_DetEnemy" },
								nil },
	{ "T_IngCrea_MothWingCyr_02", nil,
								{ id = "T_mysticism_DetHuman" },
								nil,
								nil },
	{ "T_IngCrea_MothWingSky_03", nil,
								nil,
								{ id = "T_mysticism_Blink" } },
	{ "T_IngFood_MeatDolphin_01", nil,
								nil,
								nil,
								{ id = "T_mysticism_DetHuman" } },
	{ "T_IngFlor_Indulcet_01", nil,
							 { id = "T_mysticism_DetInvisibility" },
							 nil,
							 nil },
	{ "T_IngFlor_FlaxFlower_01", nil,
								 { id = "T_mysticism_DetInvisibility" },
								 nil,
								 nil },
	{ "T_IngFlor_FlaxFlower_02", nil,
								 { id = "T_mysticism_DetEnemy" },
								 nil,
								 nil },
	{ "T_IngFlor_FlaxFlower_03", nil,
								 { id = "T_mysticism_DetHuman" },
								 nil,
								 nil },
	{ "T_IngFlor_ArrowrootFlower_01", nil,
									nil,
								 	{ id = "T_mysticism_DetEnemy" },
								 	nil },
	{ "T_IngFlor_Spiddal_01", nil,
							nil,
							nil,
							{ id = "T_mysticism_DetEnemy" } },
	{ "T_IngFlor_Peony_01", nil,
							nil,
							nil,
							{ id = "T_mysticism_DetHuman" } },
	{ "T_IngSpice_Curcuma_01", { id = "T_mysticism_ReflectDmg" },
							 nil,
							 nil,
							 nil },
	{ "T_IngCrea_CetaceanMelon", nil,
							 	 nil,
							 	 nil,
							 	 { id = "T_mysticism_ReflectDmg" } },
	{ "T_IngFlor_Siyat_01", { id = "T_mysticism_Insight" },
							nil,
							nil,
							nil },
	{ "T_IngCrea_HagravenFeathers_01", nil,
									 nil,
									 nil,
									 { id = "T_restoration_FortifyCasting" } },
	{ "T_IngSpice_Cinnamon_01", nil,
								{ id = "T_restoration_FortifyCasting" },
								nil },
	{ "T_IngMine_Spellstone_01", { id = "T_restoration_FortifyCasting" },
								 nil,
								 nil,
								 nil },
	{ "T_IngSpice_Pepper_01", nil,
							nil,
							nil,
							{ id = "T_mysticism_Insight" } },
	{ "T_IngFlor_MonksTons_01", { id = "T_mysticism_Insight" },
								nil,
								nil,
								nil },
	{ "T_IngMine_Realgar_01", nil,
							{ id = "T_mysticism_Blink" },
							nil,
							nil },
	{ "T_IngDye_WhiteLead_01", nil,
							 { id = "T_mysticism_DetValuables" },
							 nil,
							 nil },
	{ "T_IngFlor_RedrosePetal_01", { id = "T_restoration_FortifyCasting" },
								 nil,
								 nil,
								 nil },
	{ "T_IngFlor_RedrosePetalDae_01", { id = "T_restoration_FortifyCasting" },
									nil,
									nil,
									nil },
	{ "T_IngFlor_ShutagJelly_01", nil,
								nil,
								nil,
								{ id = "T_mysticism_Insight" } },
	{ "T_IngMine_Agate_01", nil,
							nil,
							{ id = "T_mysticism_Blink" },
							nil },
	{ "T_IngFlor_PilgrimGel_01", nil,
								 nil,
								 nil,
								 { id = "T_mysticism_DetEnemy" } },
	{ "T_IngFlor_PilgrimPetals_01", nil,
									nil,
									nil,
									{ id = "T_mysticism_DetInvisibility" } },
	{ "T_IngDye_Vermilion_01", nil,
							 nil,
							 nil,
							 { id = "T_mysticism_DetHuman" } },
	{ "T_IngDye_Verdigris_01", nil,
							 nil,
							 nil,
							 { id = "T_mysticism_DetValuables" } },
	{ "T_IngCrea_HopperAntler_01", nil,
								 nil,
								 nil,
								 { id = "T_mysticism_DetEnemy" } },
	{ "T_IngMine_Antimony_01", nil,
							 nil,
							 nil,
							 { id = "T_mysticism_ReflectDmg" } },
	{ "T_IngFlor_Bloatroot", nil,
							 { id = "T_restoration_FortifyCasting" },
							 nil,
							 nil },
	{ "T_IngSpice_Parsleydown_01", nil,
							 	 nil,
							 	 { id = "T_mysticism_Insight" },
								 nil },
	{ "T_IngCrea_VelkNectarSack_01", { id = "T_mysticism_DetHuman" },
							 		 nil,
							 		 nil,
									 nil },
	{ "T_IngCrea_AebisFeathers_01", nil,
									nil,
									nil,
									{ id = "T_mysticism_DetInvisibility" } },
	{ "T_IngSpice_Hibiscus_01", nil,
								nil,
								nil,
								{ id = "T_mysticism_Insight" } },
	{ "T_IngSpiceAka_Pepper_01", nil,
								 nil,
								 nil,
								 { id = "T_mysticism_ReflectDmg" } },
	{ "T_IngFood_Fig_01", nil,
						nil,
						{ id = "T_restoration_FortifyCasting" },
						nil },
	{ "T_IngCrea_Angelfish_01", nil,
								nil,
								{ id = "T_mysticism_DetValuables" },
								nil },
	{ "T_IngFood_Blueberry_01", { id = "T_mysticism_DetValuables" },
								nil,
								nil,
								nil },
	{ "T_IngFood_PoppadGourd_01", nil,
								{ id = "T_mysticism_DetHuman" },
								nil,
								nil },
	{ "T_IngFood_Blackberry_01", { id = "T_mysticism_DetInvisibility" },
								nil,
								nil,
								nil },
	{ "T_IngFood_FishSpr_01", { id = "T_mysticism_DetEnemy" },
							nil,
							nil,
							nil },
	{ "T_IngFood_FishLongfinFilet_01", nil,
									 { id = "T_mysticism_Insight" },
									 nil,
									 nil },
	{ "T_IngCrea_SnowraySting_01", nil,
								 nil,
								 nil,
								 { id = "T_restoration_FortifyCasting" } },
	{ "T_IngFood_MeatHorse_01", nil,
								{ id = "T_mysticism_DetEnemy" },
								nil,
								nil },
	{ "T_IngFood_MeatVenison_01", nil,
								{ id = "T_mysticism_DetHuman" },
								nil,
								nil },
	{ "T_IngFood_Radish_01", nil,
							 nil,
							 nil,
							 { id = "T_mysticism_Blink" } },
	{ "T_IngFood_SilverPalmfruit_01", nil,
									nil,
									nil,
									{ id = "T_mysticism_DetInvisibility" } },
	{ "T_IngFood_MeatHorker_01", nil,
								 nil,
								 nil,
								 { id = "T_mysticism_ReflectDmg" } },
	{ "T_IngFlor_HoneyLily_01", { id = "T_mysticism_Insight" },
								nil,
								nil,
								nil },
	{ "T_IngFlor_Jarmush_01", nil,
							nil,
							{ id = "T_restoration_FortifyCasting" },
							nil },
	{ "T_IngCrea_BarkHeart_01", nil,
								nil,
								nil,
								{ id = "T_mysticism_ReflectDmg" } },
	{ "T_IngFlor_Redpoppy_01", nil,
								nil,
								nil,
								{ id = "T_mysticism_Insight" } },
}

return {
	td_summon_effects = td_summon_effects,
	td_bound_effects = td_bound_effects,
	td_intervention_effects = td_intervention_effects,
	td_misc_effects = td_misc_effects,
	td_summon_spells = td_summon_spells,
	td_bound_spells = td_bound_spells,
	td_intervention_spells = td_intervention_spells,
	td_misc_spells = td_misc_spells,
	td_enchantments = td_enchantments,
	td_potions = td_potions,
	td_enchanted_items = td_enchanted_items,
	td_ingredients = td_ingredients,
}
